=== apache/lens/grill-api/src/main/resources/cube-0.1.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="uri:grill:cube:0.1"
           xmlns="uri:grill:cube:0.1"
           xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.1">
    <xs:annotation>
        <xs:appinfo>
            <jaxb:schemaBindings>
                <jaxb:package name="com.inmobi.grill.metastore.model"/>
            </jaxb:schemaBindings>
        </xs:appinfo>
    </xs:annotation>
    <xs:element name="x_cube" type="x_cube">
    </xs:element>
    <xs:complexType name="x_cube">
        <xs:annotation>
            <xs:documentation>
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="x_measures" name="measures"/>
            <xs:element type="x_dimensions" name="dimensions"/>
            <xs:element type="x_properties" name="properties" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="description"/>
        <xs:attribute type="xs:double" name="weight"/>
    </xs:complexType>
    <xs:complexType name="x_property">
        <xs:annotation>
            <xs:documentation>
                A key-value pair, which are propagated to the cube.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="value" use="required"/>
    </xs:complexType>
    <xs:complexType name="x_properties">
        <xs:annotation>
            <xs:documentation>
                A list of property elements.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="x_property" name="property" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="x_measure">
        <xs:annotation>
            <xs:documentation>
                A cube measure.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="type" use="required"/>
        <xs:attribute type="xs:string" name="defaultaggr" />
        <xs:attribute type="xs:string" name="formatString" />
        <xs:attribute type="xs:dateTime" name="starttime" />
        <xs:attribute type="xs:dateTime" name="endtime" />
        <xs:attribute type="xs:double" name="cost" />
        <xs:attribute type="xs:string" name="expr" />
        <xs:attribute type="xs:string" name="unit" />
    </xs:complexType>
    <xs:complexType name="x_measures">
        <xs:annotation>
            <xs:documentation>
                Set of measures.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="x_measure" name="measure" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="x_dimension">
        <xs:annotation>
            <xs:documentation>
                A cube dimension.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
          <xs:element type="x_tablereferences" name="references" />
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="type" use="required"/>
        <xs:attribute type="xs:dateTime" name="starttime" />
        <xs:attribute type="xs:dateTime" name="endtime" />
        <xs:attribute type="xs:double" name="cost" />
        <xs:attribute type="xs:string" name="expr" />        
    </xs:complexType>
    <xs:complexType name="x_tablereference">
        <xs:attribute type="xs:string" name="desttable" use="required"/>
        <xs:attribute type="xs:string" name="destcolumn" use="required"/>
    </xs:complexType>
    <xs:complexType name="x_tablereferences">
        <xs:sequence>
            <xs:element type="x_tablereference" name="tablereference" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
 
    <xs:complexType name="x_dimensions">
        <xs:annotation>
            <xs:documentation>
                Set of dimensions.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="x_dimension" name="dimension" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="dimension_table" type="dimension_table">
    </xs:element>
    
    <xs:complexType name="dimension_table">
        <xs:sequence>
            <xs:element type="columns" name="columns"/>
            <xs:element type="dimension_references" name="dimensions_references"/>
            <xs:element type="update_periods" name="update_periods"/>
            <xs:element type="x_properties" name="properties" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="weight" type="xs:double" />
    </xs:complexType>

    <xs:complexType name="columns">
        <xs:sequence>
            <xs:element name="columns" type="column" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="column">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" type="xs:string" use="required" />
        <xs:attribute name="comment" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="dimension_references">
        <xs:sequence>
            <xs:element name="reference" type="dimension_reference" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dimension_reference">
        <xs:sequence>
            <xs:element name="table_reference" type="x_tablereference" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="dimension_column" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="update_periods">
        <xs:sequence>
            <xs:element name="update_period_element" type="update_period_element" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="update_period_element">
        <xs:sequence>
            <xs:element name="storage_attr" type="x_storage" />
        </xs:sequence>
        <xs:attribute name="update_period" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="x_storage">
        <xs:sequence>
            <xs:element name="table_parameters" type="x_properties" />
            <xs:element name="serde_parameters" type="x_properties" />
            <xs:element name="part_cols" type="columns" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="table_type" type="xs:string" use="required"/>
        <xs:attribute name="table_location" type="xs:anyURI"/>
        <xs:attribute name="part_location" type="xs:anyURI"/>
        <xs:attribute name="input_format" type="xs:string" />
        <xs:attribute name="output_format" type="xs:string" />
        <xs:attribute name="is_compressed" type="xs:boolean" />
        <xs:attribute name="field_delimiter" type="xs:string" />
        <xs:attribute name="escape_char" type="xs:string" />
        <xs:attribute name="collection_delimiter" type="xs:string" />
        <xs:attribute name="line_delimiter" type="xs:string" />
        <xs:attribute name="map_key_delimiter" type="xs:string" />
        <xs:attribute name="serde_class_name" type="xs:string" />
    </xs:complexType>


</xs:schema>

=== apache/lens/grill-examples/src/main/resources/sample-cube.xml
<?xml version="1.0" encoding="UTF-8"?>
<x_cube name="sample_cube" xmlns="uri:grill:cube:0.1"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="uri:grill:cube:0.1 cube-0.1.xsd ">
  <measures>
    <measure name="measure1" type="long"/>
    <measure name="measure2" type="int" default_aggr="SUM"/>
    <measure name="measure3" type="float" default_aggr="MAX" start_time=2013-12-12-00:00/>
    <measure name="measure4" type="double" default_aggr="MIN"/>
    <measure name="expr_msr5" type="double" expr="measure1 + measure2" />
  </measures>
  <dimensions>
    <dimension name="dim1" type="int"/>
    <dimension name="dim2" type="int" start_time=2013-12-01-00:00/>
    <dimension name="dim3" type="int">
      <references>
        <table_references dest_table="dim_table" dest_column="id"/>
      </references>
    </dimension>
  </dimensions>
  <properties>
  <property name="sample_cube.prop" value="sample" />
  </properties>
</x_cube>
